frr version 9.1
frr defaults traditional
hostname r3
log syslog informational
!
router ospf
 ospf router-id 3.3.3.3
 network 3.3.3.3/32 area 0
 network 10.0.23.0/30 area 0
 network 10.0.31.0/30 area 0
 passive-interface lo
!
router bgp 65000
 bgp router-id 3.3.3.3
 no bgp ebgp-requires-policy
 neighbor 1.1.1.1 remote-as 65000
 neighbor 1.1.1.1 update-source lo
 neighbor 2.2.2.2 remote-as 65000
 neighbor 2.2.2.2 update-source lo
 !
 address-family l2vpn evpn
  neighbor 1.1.1.1 activate
  neighbor 2.2.2.2 activate
  advertise-all-vni
 exit-address-family
!
