frr version 9.1
frr defaults traditional
hostname r1
log syslog informational
!
router ospf
 ospf router-id 1.1.1.1
 network 1.1.1.1/32 area 0
 network 10.0.12.0/30 area 0
 network 10.0.31.0/30 area 0
 passive-interface lo
!
router bgp 65000
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 neighbor 2.2.2.2 remote-as 65000
 neighbor 2.2.2.2 update-source lo
 neighbor 3.3.3.3 remote-as 65000
 neighbor 3.3.3.3 update-source lo
 !
 address-family l2vpn evpn
  neighbor 2.2.2.2 activate
  neighbor 3.3.3.3 activate
  advertise-all-vni
 exit-address-family
!
